# Pcsx2Utils.cmake — utility macros for the PCSX2/iPSX2 build system

# Guard: abort if invoked outside the top-level CMakeLists
macro(check_no_parenthesis_in_path)
    if("${CMAKE_BINARY_DIR}" MATCHES ".*[(].*" OR "${CMAKE_SOURCE_DIR}" MATCHES ".*[(].*")
        message(FATAL_ERROR "Source or build path contains parentheses. CMake does not support this.")
    endif()
endmacro()

# Detect OS booleans used throughout the build
macro(detect_operating_system)
    if(CMAKE_SYSTEM_NAME STREQUAL "Darwin" OR IOS)
        set(APPLE TRUE)
    endif()
    if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
        set(IOS TRUE)
        set(APPLE TRUE)
    endif()
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        set(Linux TRUE)
    endif()
    if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        set(Windows TRUE)
    endif()
    if(CMAKE_SYSTEM_NAME STREQUAL "Android")
        set(ANDROID TRUE)
    endif()
endmacro()

# Detect supported compiler and set IS_SUPPORTED_COMPILER
macro(detect_compiler)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "AppleClang")
        set(IS_SUPPORTED_COMPILER TRUE)
        message(STATUS "Compiler: Clang/AppleClang — supported")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        set(IS_SUPPORTED_COMPILER TRUE)
        message(STATUS "Compiler: MSVC — supported")
    else()
        set(IS_SUPPORTED_COMPILER FALSE)
        message(WARNING "Compiler '${CMAKE_CXX_COMPILER_ID}' is not officially supported.")
    endif()
endmacro()

# Read git short hash and version tag; populate GIT_REV and GIT_TAG
macro(get_git_version_info)
    find_package(Git QUIET)
    if(GIT_FOUND)
        execute_process(
            COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
            WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
            OUTPUT_VARIABLE GIT_REV
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
        )
        execute_process(
            COMMAND ${GIT_EXECUTABLE} describe --tags --abbrev=0
            WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
            OUTPUT_VARIABLE GIT_TAG
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
        )
    endif()
    if(NOT GIT_REV)
        set(GIT_REV "unknown")
    endif()
    if(NOT GIT_TAG)
        set(GIT_TAG "0.0.0")
    endif()
    message(STATUS "Git revision: ${GIT_REV}  tag: ${GIT_TAG}")
endmacro()

# Write a minimal svnrev.h so code that includes it compiles cleanly
macro(write_svnrev_h)
    set(SVNREV_H_PATH "${CMAKE_BINARY_DIR}/common/include/svnrev.h")
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/common/include")
    file(WRITE "${SVNREV_H_PATH}"
        "// Auto-generated by CMake — do not edit\n"
        "#pragma once\n"
        "#define SVN_REV_STR \"${GIT_REV}\"\n"
        "#define SVN_MODS    0\n"
    )
endmacro()
